### PR TITLE
Create a .gitattributes

### PR DESCRIPTION
**Pull request by yogeswaran005**

### CODE REVIEW

**Comment by yogeswaran005** [comment]
Bro plz help me in this bro , plz give all files in GitHub broo , the app
is not working now broo, but before some days it's worked and I made ppt
out of it bro , now there is review bro plz help me brooo 😭😭😭😭😭😭😭
plz help me god 😭😭😭😭😭😭😭😭😭😭 iam requesting you to plz help
meeeeeee 😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭

**Comment by Harsh836-ui** [comment]
What error is coming bro

**Comment by yogeswaran005** [comment]
Bro can you guide me how create clone of your project bro

**Comment by Harsh836-ui** [comment]
try deleting older versions of code and use the new one

**Comment by yogeswaran005** [comment]
Thanks broo

**Comment by Harsh836-ui** [comment]
you use android studio or vs code

**Comment by yogeswaran005** [comment]
Android studio bro

**Comment by yogeswaran005** [comment]
Bro brooo

**Comment by yogeswaran005** [comment]
There are three warings

**Comment by yogeswaran005** [comment]
Br.com.simplepass:loding-button
Io.github.vejei.viewrepager
Com.shuhart.stepview

**Comment by yogeswaran005** [comment]
Bro help me broo

**Pull request closed without merging**
